export const Images = {
  MyCostume: {
    my_costume_gender_icon_male: require("../../assets/images/my_costume_gender_icon_male.png"),
    my_costume_gender_icon_female: require("../../assets/images/my_costume_gender_icon_female.png"),
    my_costume_gender_icon_currency: require("../../assets/images/my_costume_gender_icon_currency.png"),
    my_costume_no_clothes: require("../../assets/images/my_costume_no_clothes.png"),
    my_costume_actions_active: require("../../assets/images/my_costume_actions_active.png"),
    my_costume_actions_inactive: require("../../assets/images/my_costume_actions_inactive.png"),
    my_costume_face_active: require("../../assets/images/my_costume_face_active.png"),
    my_costume_face_inactive: require("../../assets/images/my_costume_face_inactive.png"),
    my_costume_clothes_active: require("../../assets/images/my_costume_clothes_active.png"),
    my_costume_clothes_inactive: require("../../assets/images/my_costume_clothes_inactive.png"),
    my_costume_turn_right: require("../../assets/images/my_costume_turn_right.png"),
    my_costume_turn_left: require("../../assets/images/my_costume_turn_left.png"),
    my_costume_female: require("../../assets/images/my_costume_female.png"),
    my_costume_male: require("../../assets/images/my_costume_male.png"),
    my_costume_reduction_unavailable: require("../../assets/images/my_costume_reduction_unavailable.png"),
    my_costume_reduction_available: require("../../assets/images/my_costume_reduction_available.png"),
    my_costume_next_unavailable: require("../../assets/images/my_costume_next_unavailable.png"),
    my_costume_next_available: require("../../assets/images/my_costume_next_available.png"),
    my_costume_background: require("../../assets/images/my_costume_background.png"),
    my_costume_reset: require("../../assets/images/my_costume_reset.png"),
  },
  TabStack: {
    brand_page_background: require("../../assets/images/brand_page_background.png"),
    main_page_app_icon: require("../../assets/images/main_page_app_icon.png"),
    app_icon: require("../../assets/images/app_icon.png"),
    main_page_active: require("../../assets/images/main_page_active.png"),
    main_page_inactive: require("../../assets/images/main_page_inactive.png"),
    scene_active: require("../../assets/images/scene_active.png"),
    scene_inactive: require("../../assets/images/scene_inactive.png"),
    brand_active: require("../../assets/images/brand_active.png"),
    brand_inactive: require("../../assets/images/brand_inactive.png"),
    profile_active: require("../../assets/images/profile_active.png"),
    profile_inactive: require("../../assets/images/profile_inactive.png"),
    main_page_notify: require("../../assets/images/main_page_notify.png"),
    main_page_dress_up_icon: require("../../assets/images/main_page_dress_up_icon.png"),
    main_page_character_share: require("../../assets/images/main_page_character_share.png"),
    system_message_back_icon: require("../../assets/images/system_message_back_icon.png"),
  },
}
