import { StyleSheet } from "react-native"
import { p2d } from "@/utils/commonUtils"

export default StyleSheet.create({
  bannerContainer: {
    height: p2d(120),
    width: "100%",
  },
  bodyContainer: {
    alignItems: "center",
    paddingBottom: p2d(30),
  },
  bodyPart: {
    flex: 1,
    width: "100%",
  },
  brandContainer: {
    backgroundColor: "#52C3FF",
    borderRadius: p2d(15),
    height: p2d(100),
    marginHorizontal: p2d(20),
    marginTop: p2d(20),
    width: p2d(335),
  },
  brandDesText: {
    bottom: p2d(12),
    color: "#FFF",
    fontSize: p2d(18),
    fontWeight: "bold",
    includeFontPadding: false,
    left: p2d(20),
    position: "absolute",
  },
  brandPart: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginTop: p2d(25),
    width: "100%",
  },
  brandTitle: {
    color: "#000",
    fontSize: p2d(17),
    fontWeight: "bold",
    includeFontPadding: false,
    paddingHorizontal: p2d(20),
  },
  characterBG: {
    alignItems: "center",
    backgroundColor: "#52C3FF",
    borderRadius: p2d(30),
    height: p2d(350),
    marginTop: p2d(100),
    width: p2d(325),
  },
  characterName: {
    bottom: p2d(16),
    color: "#fff",
    fontSize: p2d(20),
    fontWeight: "bold",
    includeFontPadding: false,
    position: "absolute",
  },
  characterShareBtn: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderBottomRightRadius: p2d(30),
    borderTopLeftRadius: p2d(25),
    bottom: 0,
    height: p2d(50),
    justifyContent: "center",
    position: "absolute",
    right: 0,
    width: p2d(50),
  },
  characterShareBtnImage: {
    height: p2d(26),
    width: p2d(26),
  },
  dressUpBtn: {
    alignItems: "center",
    position: "absolute",
    right: p2d(15),
    top: p2d(15),
  },
  dressUpBtnImage: {
    height: p2d(48),
    width: p2d(48),
  },
  dressUpBtnText: {
    color: "#fff",
    fontSize: p2d(13),
    fontWeight: "bold",
    includeFontPadding: false,
    marginTop: p2d(2),
  },
  sceneContainer: {
    backgroundColor: "#52C3FF",
    borderRadius: p2d(15),
    height: p2d(100),
    marginTop: p2d(20),
    paddingLeft: p2d(20),
    paddingTop: p2d(20),
    width: p2d(180),
  },
  sceneDesText1: {
    color: "#FFF",
    fontSize: p2d(18),
    fontWeight: "bold",
    includeFontPadding: false,
  },
  sceneDesText2: {
    color: "#FFF",
    fontSize: p2d(14),
    includeFontPadding: false,
    marginTop: p2d(2),
  },
  scenePart: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    marginTop: p2d(30),
    paddingHorizontal: p2d(20),
    width: "100%",
  },
  sceneTitle: {
    color: "#000",
    fontSize: p2d(17),
    fontWeight: "bold",
    includeFontPadding: false,
  },
})
